### ISSUE TITLE
Add an API query param that redirects to a populated query builder

### ISSUE THREAD

**Issue by andylolz** [codeforIATI/iati-datastore#122]
It’s good practice to share datastore queries, rather than just the output data. This makes it easier to re-run a query and reproduce results at a later date.

However, reading a long query string to try and understand what it does is difficult. And it’s even harder to then make changes to that long query string. Once it has left the query builder, it is no longer easy to edit.

It would be cool to be able to add something like `?builder=true` to an API request, and be redirected to a populated query builder. This would make it easier to inspect the query, and even to adjust and amend it.

Instead of an extra query param, we could alternatively do this via an extra URL segment.

This relies on #121, but more specifically it relies on having some way to save query builder state.

**Comment by matmaxgeds** [comment]
This would be ace in terms of making pre-made examples for people to see a sample result from, and then follow the link to tweak it to their exact needs e.g. changing the publisher, dates, or the recipient
