### ISSUE TITLE
Restore xml and json links in query builder?

### ISSUE THREAD

**Issue by matmaxgeds** [codeforIATI/iati-datastore#160]
I guess this was a deliberate decision not to offer these?

**Comment by andylolz** [comment]
I can see a "Preview as XML" link in the [DSv1 query builder](http://datastore.iatistandard.org/query/). Is that what you mean?

Or were there previously radio buttons for CSV / XML / JSON output? I suppose that would be very doable, but perhaps there’s a reason for not offering that? @markbrough

**Comment by matmaxgeds** [comment]
I was thinking about the radio buttons that used to be there.....but I suspect probs worth not deciding this in isolation but in the context of a wider thoughts about what we want the DS classic to be for (and e.g. what would be easier to maintain etc)

**Comment by markbrough** [comment]
Yes I think this is a good idea! Only very slight issue is that a couple of the options (see screenshot) don't apply to JSON and XML, so just needs a tiny bit of thought about how these options should be presented / hidden / disabled when the format is not selected as CSV

![image](https://user-images.githubusercontent.com/688113/103557588-b227d700-4eb3-11eb-95f9-3b0e26d34ca8.png)
