### ISSUE TITLE
Downloading transactions = no data

### ISSUE THREAD

**Issue by siemvaessen** [codeforIATI/iati-datastore#172]
I use https://datastore.codeforiati.org/api/1/access/transaction.csv?recipient-country=NG&stream=True but after some time an empty transactions file is provided. Would expect all transactions for NG to be there.

**Comment by andylolz** [comment]
Thanks for this, @siemvaessen – I agree that this does seem to be a problem.

I’ll close this ticket as a duplicate of #175, just so we can keep track. I’ve moved the ticket contents across, so we have a link demonstrating the problem.
