### ISSUE TITLE
Getting a 502 bad gateway

### ISSUE THREAD

**Issue by siemvaessen** [codeforIATI/iati-datastore#173]
Trying to retrieve https://datastore.codeforiati.org/api/1/access/activity.csv?recipient-country=NG&stream=True 0 but looking at a 502 Bad Gateway. I would expect data to be retrieved.

**Comment by andylolz** [comment]
This appears to be intermittent (works for me, but very slow).

The general problem here is that access is very slow, and will sometimes time out. I think we can improve this by adding some database indexes, but we haven’t sorted that yet.

**Comment by markbrough** [comment]
Agreed it would be good to look at speeding up the API - we haven't really done any work on this yet! Though NB it is running on a very cheap server!

I just did a quick test and this downloads in 24 seconds:
https://datastore.codeforiati.org/api/1/access/activity.xml?recipient-country=NG&stream=True

This (from the v2 Datastore) downloads in 44 seconds:
https://iatidatastore.iatistandard.org/search/activity?q=((recipient_country_code:NG)%20OR%20(transaction_recipient_country_code:NG))&wt=xslt&tr=activity-xml.xsl&rows=100000000

There's also a difference in the total file size which would be good to look into:

Service | Time | Size
--- | --- | ---
IATI Datastore | 44s | 319.44MB
Datastore Classic | 24s | 106.73MB

**Comment by andylolz** [comment]
I’m suspicious that this is an nginx issue. This looks like it might help:
https://riptutorial.com/flask/example/16288/enable-streaming-from-flask

**Comment by siemvaessen** [comment]
Pretty sure the file size has to do with the datastore classic being incomplete (not all fields etc). Also one of the reasons I am not sure why you would put any efforts on this work unless it's for older projects that you need to support?

**Comment by markbrough** [comment]
The above comparison is for the XML file size, which should be very similar, considering that the number of activities for Nigeria is quite similar.

Service | Number of activities for Nigeria
--- | ---
IATI Datastore | 10,260
Datastore Classic | 10,622

**Comment by siemvaessen** [comment]
Well, they should. To my knowledge Datastore V1 does not cover all fields hence the difference.

**Comment by markbrough** [comment]
Sort of. It only stores certain fields in the database (so [only those fields are searchable](https://datastore.codeforiati.org/docs/api/#filtering)). However, it stores the original blob of XML. So for example you will see that this XML is complete (and the original, untouched XML):
https://datastore.codeforiati.org/api/1/access/activity.xml?iati-identifier=44000-P125574

The JSON output is also wrangled on the fly from the original XML blob, so it's also complete (from a quick glance):
https://datastore.codeforiati.org/api/1/access/activity/?iati-identifier=44000-P125574

There is also an option to get JSON output based on piecing data together from the database:
https://datastore.codeforiati.org/api/1/access/activity.db.json?iati-identifier=44000-P125574

You can see the last link is much less complete, but the other two links should be the full set of data.

**Comment by siemvaessen** [comment]
Not so interested in the original XML (that can be found anywhere) but mainly interested in Datastore V1 provides incomplete data and therefore imho should never be used in a live scenario. Hence IATI has decommissioned this piece of software all together.

Anyway, this is in no way related to the 502 bad gateway which is solved, so closing this issue!

**Comment by markbrough** [comment]
Sure, makes sense to close this issue. I spun off an investigation of differences in total file size to #185 as it would be good to understand if e.g. there are activities missing from the output.

Just to clarify, the XML and JSON data does appear to be complete in Datastore Classic when accessed through the above links. NB, Datastore Classic contains more activities than in the v1 and v2 Datastores. I appreciate that you might not be interested in the original XML, but this is important for certain use cases and consistent with the way the v1 Datastore functions.

**Comment by siemvaessen** [comment]
> would be good to understand if e.g. there are activities missing from the output.

That is rather obvious.. As per IATI  Members Assembly agreement it was decided to not include invalid data which DSv1 still does. So obviously it will contain more activities as it simply accepts anything. So best to make DSv1 only accepts validated data otherwise its comparing apples to pears.

> Datastore Classic contains more activities than in the v1 and v2 Datastores

Again, you can not compare the two as they have a different set of business rules to adhere to. DSv1 having no rules (?) I think and DSv2 have some rules in place wrt valid IATI data.


> the original XML

Anyone could just grab original XML from the Registry, not sure what's so special about storing original XML (DSv2 does it as well). So you could also use DSv2 if your case is about access to original XML files should you need them for your usecase.

**Comment by markbrough** [comment]
Thanks @siemvaessen - the intention is for Datastore Classic to accept as much data as possible. We are not excluding v1 data or data that does validate against the schema, though there is a separate issue #182 to make it possible to select only valid or only invalid activities.

Also, the point of comparing the two is not to show that one is better than the other. It is just to identify issues.
