### ISSUE TITLE
Query builder generates bad URL when stream=True is selected

### ISSUE THREAD

**Issue by siemvaessen** [codeforIATI/iati-datastore#174]
Go to: https://datastore.codeforiati.org/

Status message = Datastore fully operational

But when trying to access data no data is available.

**Comment by andylolz** [comment]
> But when trying to access data no data is available.

Works for me… https://datastore.codeforiati.org/api/1/access/activity/ returns:
![Screenshot 2021-01-06 at 15 15 46](https://user-images.githubusercontent.com/464193/103784604-107ac400-5032-11eb-95fc-c968fe8e66ad.png)

Could you provide a link that illustrates the problem you’re seeing, @siemvaessen? Thanks

**Comment by siemvaessen** [comment]
Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

@

https://datastore.codeforiati.org/api/1/access/activity.csv&stream=True

**Comment by andylolz** [comment]
Ah okay. I think that’s because you have a `&` where you should have a `?`.

That said, https://datastore.codeforiati.org/api/1/access/activity.csv?stream=True returns a 502 error! But let’s track that bug in #175.

**Comment by andylolz** [comment]
> https://datastore.codeforiati.org/api/1/access/activity.csv&stream=True

Ooh – I’ve just spotted where that URL has most likely come from… Looks like a bug with the query builder:
https://datastore.codeforiati.org/?stream=true

**Comment by siemvaessen** [comment]
Has this been deployed yet?

**Comment by andylolz** [comment]
Apologies – I’ve just deployed it now.
