### ISSUE TITLE
Only 50 sample size works for CSV downloads?

### ISSUE THREAD

**Issue by siemvaessen** [codeforIATI/iati-datastore#175]
Seems only 50 sample size works for downloads? I Tried with country Kenya.

Tried it with all activities, but then nothing comes out. Would expect all activities to be downloaded for Kenya.

**Comment by andylolz** [comment]
Copying over from #172 (which I think points to the same problem as this ticket):

> I use https://datastore.codeforiati.org/api/1/access/transaction.csv?recipient-country=NG&stream=True but after some time an empty transactions file is provided. Would expect all transactions for NG to be there.

**Comment by andylolz** [comment]
By the way, thanks for raising this, @siemvaessen! It does appear there’s a problem here.

**Comment by markbrough** [comment]
Agreed, it looks like there is an issue when you download CSV files with `&stream=True`

**Comment by andylolz** [comment]
I’ve sent a fix for this now.

Looks as though I introduced this bug to IATI’s master branch 2 years ago. I don’t think it ever showed up in production, because I suspect my fix was never deployed. The `live` branch was updated 2.5 years ago, so doesn’t include this bug.

**Comment by siemvaessen** [comment]
has this fix been deployed?

**Comment by andylolz** [comment]
> has this fix been deployed?

Yes – try your link:
> I use https://datastore.codeforiati.org/api/1/access/transaction.csv?recipient-country=NG&stream=True but after some time an empty transactions file is provided. Would expect all transactions for NG to be there.

**Comment by andylolz** [comment]
> has this fix been deployed?

Yes – [try your link above](https://github.com/codeforIATI/iati-datastore/issues/175#issuecomment-755366058). It seems to be working for me.

**Comment by andylolz** [comment]
@siemvaessen we’ve fixed #183 now, so any PRs that are merged will be auto-deployed.
