### ISSUE TITLE
"Checking Datastore status..." on the homepage takes A Long Time

### ISSUE THREAD

**Issue by andylolz** [codeforIATI/iati-datastore#187]
It’s because /api/1/about/ is quite slow.

It looks like the slow bit is counting the number of activities and transactions.

It would be nice to speed this up!

**Comment by siemvaessen** [comment]
Cache it!

**Comment by andylolz** [comment]
> Cache it!

I think Mark is looking at storing some basic stats in a separate table that gets updated on a trigger.
