### ISSUE TITLE
Add IATI identifier

### ISSUE THREAD

**Issue by matmaxgeds** [codeforIATI/iati-datastore#191]
The DSv2 usefully (I think) adds the IATI identifier to each result returned......needs thinking through why this was not in the original spec, by maybe worth adding as I think it should be non-breaking for most parsers

**Comment by andylolz** [comment]
Not sure I follow… Could you provide a DS classic URL to illustrate? (E.g. is this for transaction and budget queries?)

**Comment by matmaxgeds** [comment]
Closing........too early in the morning, I just missed where it was hiding in DS Classic!
