### ISSUE TITLE
Query builder: in chrome I get this annoying autocomplete popup for recipient location fields

### ISSUE THREAD

**Issue by andylolz** [codeforIATI/iati-datastore#196]
### Screenshots

![Screenshot 2021-01-08 at 17 53 59](https://user-images.githubusercontent.com/464193/104048129-acdfca80-51da-11eb-8097-47b159ed8cb6.png)

### To Reproduce

Steps to reproduce the behaviour:

1. Go to https://datastore.codeforiati.org/ in chrome
2. Click on the recipient country dropdown
3. See autocomplete dialog

### Additional context

I guess `autocomplete="off"` would fix this?

**Comment by markbrough** [comment]
Hmm this seems very weird - I don't have the same behaviour in Chrome. Perhaps it is a particular plugin in your browser?

It looks here like autocomplete is turned off by default:
https://vue-select.org/api/props.html#autocomplete

Though perhaps this is also relevant:
https://vue-select.org/guide/accessibility.html

**Comment by andylolz** [comment]
Ohh okay… Looks like it is this: chrome://settings/addresses

**Comment by andylolz** [comment]
This issue is pretty specific (chrome with autofill switched on) and the fix looks super ugly. So I’m going to close this as `wontfix`.
