### ISSUE TITLE
Query builder dropdowns have become very narrow

### ISSUE THREAD

**Issue by andylolz** [codeforIATI/iati-datastore#211]
### Describe the bug

Not sure what has gone wrong here!
![Screenshot 2021-01-11 at 15 47 56](https://user-images.githubusercontent.com/464193/104203814-77c6b880-5424-11eb-90c4-e13360da0644.png)

**Comment by andylolz** [comment]
It looks like I broke this in #208, but I do not understand how!

**Comment by markbrough** [comment]
This issue has reappeared (I think for the same reason) -- though it doesn't make sense to me... looking into it!

**Comment by markbrough** [comment]
So it looks like, when `<b-navbar-brand>` looks like this (which seems correct, according to [the Bootstrap-Vue documentation](https://bootstrap-vue.org/docs/components/navbar)):

```html
<b-navbar-brand href="https://codeforiati.org">
  <img
    width="100px"
    src="https://codeforiati.org/assets/img/logo.png"
    title="A project of Code for IATI" >
</b-navbar-brand>
```
`<v-select>` is not rendered as actual HTML.

By contrast, when it looks like this (incorrectly, according to the documentation):

```html
<b-navbar-brand href="#">
  <a href="https://codeforiati.org">
    <img
      width="100px"
      src="https://codeforiati.org/assets/img/logo.png"
      title="A project of Code for IATI" />
  </a>
</b-navbar-brand>
```

`<vue-select>` is correctly rendered as actual HTML.

An additional complication: when rendering "incorrectly" with the Code for IATI Sidebar, the brand image appears twice. (!!!)
