### ISSUE TITLE
`unwrap=True` unnecessarily triggers `.count()`, which is slow

### ISSUE THREAD

**Issue by markbrough** [codeforIATI/iati-datastore#235]
### Describe the bug

When adding `unwrap=True` to a query URL, it looks like `.count()` is triggered. Given that we know postgres is quite slow at doing COUNT, it would be good to avoid this as I think it would speed up certain queries up quite a lot. For example, this query is quite slow:

https://datastore.codeforiati.org/api/1/access/activity.xml?title=National%20Statistics%20Systems%20Strengthening%20(NSSS%20-MDTF)&reporting-org=US-GOV-1&limit=10&unwrap=True

Whereas running this on the database is fast:

```sql
SELECT COUNT(id) FROM activity 
JOIN organisation ON organisation.id=activity.reporting_org_id 
WHERE activity.title LIKE '%National Statistics Systems Strengthening (NSSS -MDTssF)%'
AND organisation.ref = 'US-GOV-1' 
LIMIT 10;
```

**Comment by andylolz** [comment]
Ooh, good spot!

So one issue here is: The datastore likes to return a 404 if the offset is greater than the total. In order to do this, it needs to compute the total.

I don’t really like this – I think in such cases, we should probably just return an empty list. What do you think?
