### ISSUE TITLE
CSV transactions download is very slow

### ISSUE THREAD

**Issue by siemvaessen** [codeforIATI/iati-datastore#240]
Tried downloading all transactions for Nigeria. Took me 45 mins to get a 400MB and it was still downloading. I manually stopped it as it seemed it was not going to stop.

**Comment by andylolz** [comment]
Thanks Siem – could you include the link you used?

**Comment by siemvaessen** [comment]
owh yes - https://datastore.codeforiati.org/api/1/access/transaction.csv?recipient-country=NG&stream=True

Doing too many things at the same time... sorry.

**Comment by andylolz** [comment]
Nice – thank you!
