### ISSUE TITLE
Database sometimes timing out

### ISSUE THREAD

**Issue by markbrough** [codeforIATI/iati-datastore#250]
### Describe the bug

The page https://datastore.codeforiati.org/api/1/about/ is sometimes erroring, with the following error message in the logs:

```
ERROR in app: Exception on /api/1/about/ [GET]
Traceback (most recent call last):
  File "/home/admin/iati-datastore/pyenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/admin/iati-datastore/pyenv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
psycopg2.OperationalError: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
```

### To Reproduce

Steps to reproduce the behaviour:

1. Go to https://datastore.codeforiati.org/api/1/about/
2. Refresh a few times
3. See the bug
4. Look in `/var/log/uwsgi/iati-datastore_uwsgi.log`
5. See the above error message

(I'm struggling to reproduce this now, though it was happening frequently earlier)

### Expected behaviour

Database shouldn't time out

**Comment by markbrough** [comment]
This may also have been caused by excessive memory usage.

https://stackoverflow.com/questions/35709824/is-uwsgis-reload-on-rss-per-worker-process

I reduced the number of processes and set to reload after serving the request when any process exceeds 256MB of memory by adding the following lines to `iati-datastore_uwsgi.ini`:
```ini
processes = 4
reload-on-rss = 256
```

The largest active processes can be found by running:

```bash
ps aux --sort -rss | head -n10
```

**Comment by markbrough** [comment]
Might also be worth taking another look at this, as the `journalctl` memory usage can get quite high

https://blog.kylemanna.com/linux/systemd-journalctl-memory-hog/

**Comment by matmaxgeds** [comment]
Just to confirm that I have experienced this bug also

**Comment by markbrough** [comment]
Thanks @matmaxgeds -- the issue should now be resolved, but please flag if you see it again!

**Comment by markbrough** [comment]
Cautiously optimistic that this issue is now resolved - it hasn't appeared in the last 24 hours. Will keep this issue open a little longer just in case!

**Comment by markbrough** [comment]
Doesn't appear to be an issue anymore, since we used to new more powerful servers.
