### ISSUE TITLE
Add notice welcoming new users

### ISSUE THREAD

**Issue by markbrough** [codeforIATI/iati-datastore#261]
### Is your feature request related to a problem? Please describe.

The IATI website is now pointing users towards Code for IATI's Datastore Classic, while the official IATI Datastore is experiencing downtime.

### Describe the solution you’d like

Add a notice welcoming users and asking them to get in touch with us, so that we can be more aware of who our users are and their needs

**Comment by andylolz** [comment]
🎉 🎉 🎉
