### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by markbrough** [codeforIATI/iati-datastore#269]
### Is your feature request related to a problem? Please describe.

It would be useful to have analytics tracking usage of Datastore Classic. Logs show a number of different users, and it would be useful to understand this better.

### Describe the solution you’d like

Perhaps using something like https://matomo.org/
e.g. there could be a very simple integration with Flask: https://github.com/Lanseuo/flask-matomo
-- though might be sensible to run this `after_request()` rather than `before_request()`

### Describe alternatives you’ve considered

Google Analytics would be nice to avoid if possible -- Matomo can be self-hosted and looks quite easy to integrate with APIs, as well as with the nuxt.js frontend: https://www.npmjs.com/package/nuxt-matomo

**Comment by odscjames** [comment]
We have used Matomo before and are happy to again. Questions I can think of so far:

1) Do you have a particular instance or SaS service you'd like to use? We can discuss options if not.

2) You mention a Python library that posts straight to Matomo from the Datastore server. In the past we've just used the Javascript widget - and you link to a library to do that. Which one do we want to do? I'm not sure it's possible to use both and still make sure the stats you get at the other end are not double-counted - I can look into that if wanted? There are pros & cons to either:
* Python: Will log API access that does not involve a web browser
* Javascript: More information will be recorded (eg screen resolution)
* Python: will also record a lot of useless bot traffic that any web site online gets these days which we would then have to filter out (eg search engine bots, SEO crawlers )
* Javascript: possible to block (tho see next point)


3) Has anyone considered the various privacy, GDPR etc implications, do we need to add notices / permission checks?

**Comment by markbrough** [comment]
1. Nope! Let's discuss.

2. I think it would be good to use Python, because a number of systems / services should be accessing Datastore Classic routinely without using the web front-end, and actually one of the main priorities is tracking this usage. I would guess that Matomo has ways of filtering out useless bot traffic?
    
    I think Python would be sufficient to begin with. But if there would be advantages and if it would not be too complicated, then we could include both Javascript and Python? In any case, I think we would want to avoid using cookies so that we don't need a cookie notice.

3. We will add a privacy policy and make clear that we are processing the data on the basis of legitimate interests: https://matomo.org/blog/2018/04/lawful-basis-for-processing-personal-data-under-gdpr-with-matomo/
    
    It looks like it's also possible to enable some features in Matomo to avoid processing personal data:
https://matomo.org/blog/2018/04/how-to-not-process-any-personal-data-with-matomo-and-what-it-means-for-you/

**Comment by odscjames** [comment]
2)

While doing some research into Javascript & Python & Double Counting, I came across a comment and realised something: If we add a reverse proxy to the API methods then the Python counting will break, as not all hits will be counted. 

Instead, maybe we could try Apache log importing? https://matomo.org/log-analytics/ https://matomo.org/docs/log-analytics-tool-how-to/ This has the added benefit of having features to take out bot traffic. However it requires SSH access to the matomo server, so that may limit our hosting choices.

Also, on the double counting problem - I've realised we could just employ an iterative approach here. We can use different Matomo sites to keep the traffic from different methods totally separate for now. That will enable us to get this started faster. Then after we have a bit of traffic from both methods, we can review and change as needed.

**Comment by markbrough** [comment]
Apache log importing sounds like it would be a great place to start! Definitely happy with an iterative approach to this.

**Comment by odscjames** [comment]
https://matomo.org/faq/log-analytics-tool/#faq_16307 The Double Counting problem is not fixed - official advice is to use separate site ID's. We'll do that then.

**Comment by odscjames** [comment]
Am working on importing Apache logs and having a few issues:

1)

The URL is not being extracted properly and the "http" bit is missing, which makes Matomo extract the path badly.

2)

https://github.com/matomo-org/matomo-log-analytics is the Python import script to Matomo.

It deliberately filters out any xml, json, csv files as static files or downloads that should be ignored, and I can't find a way to pass command line options to change that behavior.

Maybe we'll have a better idea, but I'm thinking of asking you to fork https://github.com/matomo-org/matomo-log-analytics commit 6a0dae6126b97bd083cd5a48b598526bb25f0509 (this is the commit for 4.4.1 of Matomo, the latest) into your organisation and give me access. I'll then make a tiny edit to remove those 3 file types from the variables at the top of the file and this problem will be fixed. Not ideal, as then we'll have to keep it up to date but there we go :-(

**Comment by markbrough** [comment]
Hi @odscjames - I think you can add the argument `--enable-static`

I used this (German!) tutorial which seemed to work:

https://wp-typ.de/entwicklung/matomo-logging-aus-nginx/

NB the log format should be `--log-format-name=ncsa_extended`

If this doesn't work, I'm very happy to deploy a different commit as you suggest.

**Comment by odscjames** [comment]
>  I think you can add the argument --enable-static

Yes, but there is no corresponding argument enable-download :-(

I tried passing --download-extensions=zip but annoyingly if you pass --download-extensions it will check both the list you pass AND the list it has built in. There appears to be no way to remove extensions. There is --add-download-extensions but no remove!

> NB for nginx, the log format should be --log-format-name=ncsa_extended - not sure about Apache

I'm telling Apache to use the custom log format from their own readme, which is why it's annoying that there then seems to be a problem :-(

I'll read over that German page later to see if it helps any.

**Comment by odscjames** [comment]
Ah hold on - been doing some reading around downloads and it looks like something else might be going on here - it's ok that they are flagged as downloads as they should still be being reported to Matomo. So maybe something else was causing issues here. I'll check this out.

**Comment by odscjames** [comment]
Logging from server to Matomo directly is now working.

For adding the Javascript logging, the app now has the following env vars it can use:
* MATOMO_HOST (form `https://domain/` only - doesn't have the `/matomo.php` bit at end)
* MATOMO_SITEID
* MATOMO_TOKEN (not needed for JS logging but I thought I might as well while I'm doing the other 2, it may be wanted later)

**Comment by odscjames** [comment]
TODO: Make sure our import Python script is documented properly

**Comment by odscjames** [comment]
Meeting today - we won't add front end logging. Close this ticket when documentation done.

**Comment by odscjames** [comment]
https://github.com/OpenDataServices/iati-data-store-classic-matomo-import/blob/main/README.md
