### ISSUE TITLE
Set up continuous deployment for ODS server

### ISSUE THREAD

**Issue by markbrough** [codeforIATI/iati-datastore#278]
### Is your feature request related to a problem? Please describe.

The Code for IATI server has continuous deployment set up, which significantly simplifies the deployment process as the latest changes to the code are automatically deployed as soon as a PR is merged to the `main` branch. However, this is not currently set up on the ODS server.

### Describe the solution you’d like

Set up continuous deployment on the ODS server using Github Actions.

### Describe alternatives you’ve considered

Deploying manually.

**Comment by odscjames** [comment]
#289

**Comment by odscjames** [comment]
https://github.com/codeforIATI/iati-datastore/runs/3599274834?check_suite_focus=true is run on main and deployed to live server, seen auth sys log messages on live server as they logged in then ran the sudo commands, seen commits of #289 arrive on live server. looking good!
