### ISSUE TITLE
Want a dev vagrant box in the repository?

### ISSUE THREAD

**Issue by odscjames** [codeforIATI/iati-datastore#284]
### Is your feature request related to a problem? Please describe.

Make it really easy for dev's to set up environments that mirror live as much as possible.

### Describe the solution you’d like

I've set up a vagrant box on my laptop that is basically working - is there interest in having this checked in? I would just add some docs quickly.

### Describe alternatives you’ve considered

Docker Compose, but I felt with Vagrant it was faster for me to match the live environment.

### Additional context

n/a

**Comment by markbrough** [comment]
Yup please do check it in if it's quick and easy! But as discussed before -- it's not a big priority so please don't spend a lot of time on it.

**Comment by odscjames** [comment]
Done
