### ISSUE TITLE
Move issues over from IATI repo

### ISSUE THREAD

**Issue by matmaxgeds** [codeforIATI/iati-datastore#3]
There is a lot of useful information in the issues in the IATI DS repo: https://github.com/IATI/IATI-Datastore/issues, as well as things that could be fixed.

There are tools that can help with this process e.g.: https://github.com/E3V3A/gh-missue

**Comment by andylolz** [comment]
[Running this now!](https://github.com/E3V3A/gh-missue) It’s very slow, but it’s doing the trick.

**Comment by markbrough** [comment]
Done! 👍
