### ISSUE TITLE
Duplication of a sector code - 12196

### ISSUE THREAD

**Issue by matmaxgeds** [codeforIATI/iati-datastore#348]
I was adding some sectors via the query builder and found a duplicate code - see screenshot - 12196 Medical Health Statistics and Data, neither of the two options added themselves properly.
![Screenshot from 2022-03-09 19-53-29](https://user-images.githubusercontent.com/432153/157516230-fd59fafb-3213-4d34-8639-206287f25d74.png)

**Comment by markbrough** [comment]
This is fixed now in https://github.com/codeforIATI/IATI-Codelists-NonEmbedded/pull/79
