### ISSUE TITLE
Occasional full re-import

### ISSUE THREAD

**Issue by andylolz** [codeforIATI/iati-datastore#62]
Makes a lot of assumptions about what data it doesn't need to import, and I've not yet convinced myself that it's not missing anything.

Should we reimport everything occasionally?

**Comment by andylolz** [comment]
> Makes a lot of assumptions about what data it doesn't need to import

I think this was certainly true, but I don’t think it’s the case anymore. I think we can safely close, and drop the idea of full re-imports.

**Comment by markbrough** [comment]
Agreed!
