### ISSUE TITLE
Improve support for new transaction level elements

### ISSUE THREAD

**Issue by andylolz** [codeforIATI/iati-datastore#74]
Currently there is no filter for these. It will need to be decided whether they should have their own filter, or whether they should be included in the current activity level filters.

Also the by_sector and by_country CSVs currently only filter on the activity level elements.

Split out from https://github.com/IATI/iati-datastore/issues/226

**Comment by markbrough** [comment]
I think the default functionality should be for filters to search on either activity or transaction level - in common with this precedent:
https://github.com/codeforIATI/iati-datastore/blob/ef42018c1f63895966aecbbc1f34914889bfc13d/iati_datastore/iatilib/frontend/dsfilter.py#L83-L90
