### ISSUE TITLE
Use of Query Strings restricts long queries

### ISSUE THREAD

**Issue by andylolz** [codeforIATI/iati-datastore#77]
x-posting from IATI/IATI-Query-Builder#15

There is a [defacto limit of 2000 characters](http://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers) in a URL. When building up a complex query, this limit can be hit. As such, it may be preferable to use other methods to build up a query, such as POST data.

**Comment by andylolz** [comment]
(I was unable to see another issue in this repo noting this problem, though may well have missed something!)

**Comment by markbrough** [comment]
This appears to only be an issue for extremely old versions of IE, for users who have long and complicated queries. This is an extremely small and unlikely edge case. One way of handling this would be to add POST requests for all the API endpoints, but that doesn't feel like how this API should work, and is not a good use of time for something that is so unlikely to occur.
