### ISSUE TITLE
No currency information in budget CSV

### ISSUE THREAD

**Issue by andylolz** [codeforIATI/iati-datastore#78]
https://datastore.codeforiati.org/api/1/access/budget.csv

**Comment by andylolz** [comment]
^^ that URL should be:
http://datastore.iatistandard.org/api/1/access/budget.csv

**Comment by stevieflow** [comment]
@andylolz mind if I close this in favour of https://github.com/codeforIATI/iati-datastore/issues/371 - where there's a bit more info?

(apologies - I didn't search for previous issues)

**Comment by andylolz** [comment]
Yeah sure, no problem.
