### ISSUE TITLE
https support

### ISSUE THREAD

**Issue by andylolz** [codeforIATI/iati-datastore#81]
Would be great if the datastore could be served over https as well as / instead of http.

Context:
I’d like to use the datastore API in javascript on an HTTPS site, but I can’t because of mixed content errors. Adding an SSL certificate and serving datastore content over HTTPS would therefore be great.

**Comment by andylolz** [comment]
Thanks @andylolz - we've added this to our list of weekly maintenance jobs.

**Comment by markbrough** [comment]
Done! This is now super straightforward with certbot.
